name: Cypress Tests

on:
  push:
    branches:
      - main
      - dev

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    env:
      CYPRESS_STANDARD_USER: ${{ secrets.CYPRESS_STANDARD_USER }}
      CYPRESS_PROBLEM_USER: ${{ secrets.CYPRESS_PROBLEM_USER }}
      CYPRESS_LOCKED_USER: ${{ secrets.CYPRESS_LOCKED_USER }}
      CYPRESS_ERROR_USER: ${{ secrets.CYPRESS_ERROR_USER }}
      CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests with reporter
        run: npm run test:ci

      - name: Merge reports
        run: npm run prepare:report

      - name: Generate HTML report
        run: npm run report:html

      - name: Upload HTML report artifact
        uses: actions/upload-artifact@v4
        with:
          name: cypress-html-report
          path: cypress/reports/index.html